<?php

$out .= '<form method="post" autocomplete="off">';
$out .= '<div class="panel panel-primary">';
$out .= '<div class="panel-heading"> ';
$out .= '<h3 class="panel-title">ACCOUNT REGISTRATION</h3>';
$out .= '</div>';
$out .= '<div class="panel-body">';
$out .= '<div class="alert alert-warning">';
$out .= '<h3><strong></strong></h3>';
$out .= '<p><b></b></p>';
$out .= '<div><b>• New Account Registration is OPEN.</b></div>';
$out .= '<div><b>• Email Confirmation NOT Required.</b></div>';
$out .= '<div><b>• Username and Password are case-sensitive.</b></div>';
$out .= '<p></p>';
$out .= '<br>';
$out .= '</div>';
$out .= '<table class="table">';
$out .= '<tbody>';
$out .= '<tr>';
$out .= '<th class="success" width="15%" nowrap=""><i class="fa-solid fa-user"></i> Username</th>';
$out .= '<td><input type="text" autocomplete="off" class="form-control" name="username" placeholder="Username length must be between 4 to 12 characters only." maxlength="12" value="'. $username .'" pattern="[a-zA-Z0-9]{4,12}" required=""></td>';
$out .= '</tr>';
$out .= '<tr>';
$out .= '<th class="success" width="15%" nowrap=""><i class="fa-solid fa-lock"></i> Password</th>';
$out .= '<td><input type="password" autocomplete="off" class="form-control" name="password" placeholder="Password length must be between 4 to 12 characters only." maxlength="12" value="'. $password .'" pattern="[a-zA-Z0-9]{4,12}" required=""></td>';
$out .= '</tr>';
$out .= '<tr>';
$out .= '<th class="success" width="15%" nowrap=""><i class="fa-solid fa-lock"></i> Confirm Password</th>';
$out .= '<td><input type="password" autocomplete="off" class="form-control" name="confirmPassword" placeholder="Re-type your Password." maxlength="12" value="'. $confirmPassword .'" pattern="[a-zA-Z0-9]{4,12}" required=""></td>';
$out .= '</tr>';
$out .= '<tr>';
$out .= '<th class="success" width="15%" nowrap=""><i class="fa-solid fa-envelope"></i> Email Address</th>';
$out .= '<td><input type="email" autocomplete="off" class="form-control" name="email" placeholder="Please make sure you enter a valid and working Email." maxlength="50" value="'. $email .'" pattern=".{4,50}" required=""></td>';
$out .= '</tr>';
$out .= '<tr>';
$out .= '<th class="success" width="15%" nowrap=""><i class="fa-solid fa-envelope"></i> Confirm Email Address</th>';
$out .= '<td><input type="email" autocomplete="off" class="form-control" name="confirmEmail" placeholder="Re-type your Email." maxlength="50" value="'. $confirmEmail .'" pattern=".{4,50}" required=""></td>';
$out .= '</tr>';
$out .= '<tr>';
$out .= '<th class="success" width="15%" nowrap=""><i class="fa-solid fa-list-ol"></i> PIN</th>';
$out .= '<td><input type="text" name="pin" autocomplete="off" class="form-control" placeholder="PIN must be 6 digits of number. REMEMBER YOUR PIN!" maxlength="6" pattern="[0-9]{6}" value="'. $pin .'"  required oninput="if (!window.__cfRLUnblockHandlers) return false; this.value=this.value.replace(/[^0-9]/g, ``);"></td>';
$out .= '</tr>';
$out .= '<tr><td></td></tr>';
$out .= '<tr><td colspan="2" style="padding : 0"><div class="cf-turnstile" data-sitekey="'. antiject($publickey) .'"></div></div></td></tr>';
$out .= '<tr><td></td></tr>';
$out .= '<tr>';
$out .= '<td colspan="2" style="padding : 0"><button type="submit" class="btn btn-success">Register</button><input type="hidden" name="page" value="register"></td>';
$out .= '</tr>';
$out .= '</tbody></table>';
$out .= '</div>';
$out .= '</div>';
$out .= '</form>';