<?php

$out .= '<style>table > thead > tr > th, .table > tbody > tr > th, .table > tfoot > tr > th, .table > thead > tr > td, .table > tbody > tr > td, .table > tfoot > tr > td {border-top : 0px;}</style>';
$out .= '<div class="panel panel-primary">';
$out .= '<div class="panel-heading">';
$out .= '<h3 class="panel-title">TERMS AND AGREEMENT</h3>';
$out .= '</div>';
$out .= '<div class="panel-body">';
$out .= '<form method="post" autocomplete="off"> ';
$out .= '<table class="table">';
$out .= '<tbody><tr>';
$out .= '<th><h2 style="color:red;">Please read carefully before continue!</h2></th>';
$out .= '</tr>';
$out .= '<tr class="success">';
$out .= '<th>• Your account will be your 100% responsibillity, keep your account information safe and never share your account information to other person.</th>';
$out .= '</tr>';
$out .= '<tr class="success">';
$out .= '<th>• If you get hacked / simmiliar problem its not our Team responsibillity.</th>';
$out .= '</tr>';
$out .= '<tr class="success">';
$out .= '<th>• Admin may see/change your account information for some case (investigation / simmiliar problem).</th>';
$out .= '</tr>';
$out .= '<tr class="success">';
$out .= '<th>• Donation needed to keep server alive, if you decided to Donation you are not allowed to cancel/refund/reversal the payment.</th>';
$out .= '</tr>';
$out .= '<tr class="success">';
$out .= '<th>• You must agree and follow INGAME RULES.</th>';
$out .= '</tr>';
$out .= '<tr>';
$out .= '<th class="warning">Terms and Agreement might changed/updated without notice.</th>';
$out .= '</tr>';
$out .= '<tr>';
$out .= '<th><h2 style="color:red;"><div>By Clicking Agree &amp; Continue</div><div>You are agree to Terms and Agreement above.</div></h2></th>';
$out .= '</tr>';
$out .= '<tr>';
$out .= '<th><a href="index.php" class="btn btn-primary"><i class="fa-solid fa-arrow-left"></i> Back</a> &nbsp;&nbsp;&nbsp; <button type="submit" class="btn btn-success"><i class="fa-solid fa-check"></i> Agree &amp; Continue</button></th>';
$out .= '</tr>';
$out .= '</tbody>';
$out .= '</table>';
$out .= '<input type="hidden" name="page" value="terms">';
$out .= '</form>';
$out .= '</div>';
$out .= '</div>';
